import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        base:            "var(--bg-base)",
        elevated:        "var(--bg-elevated)",
        sidebar:         "var(--bg-sidebar)",
        card:            "var(--bg-card)",
        "card-hover":    "var(--bg-card-hover)",
        border:          "var(--border)",
        "border-subtle": "var(--border-subtle)",
        "border-strong": "var(--border-strong)",
        foreground:      "var(--text-foreground)",
        secondary:       "var(--text-secondary)",
        muted:           "var(--text-muted)",
        subtle:          "var(--text-subtle)",
        disabled:        "var(--text-disabled)",
        accent: {
          DEFAULT:    "var(--accent)",
          hover:      "var(--accent-hover)",
          active:     "var(--accent-active)",
          muted:      "var(--accent-muted)",
          glow:       "var(--accent-glow)",
          foreground: "var(--accent-foreground)",
        },
        energy: {
          DEFAULT: "var(--energy)",
          muted:   "var(--energy-muted)",
          glow:    "var(--energy-glow)",
        },
        success:         "var(--success)",
        "success-muted": "var(--success-muted)",
        warning:         "var(--warning)",
        "warning-muted": "var(--warning-muted)",
        danger:          "var(--danger)",
        "danger-muted":  "var(--danger-muted)",
        info:            "var(--info)",
        "info-muted":    "var(--info-muted)",
      },
      fontFamily: {
        sans:    ["var(--font-body)", "DM Sans", "system-ui", "sans-serif"],
        heading: ["var(--font-heading)", "Plus Jakarta Sans", "system-ui", "sans-serif"],
        mono:    ["var(--font-mono)", "JetBrains Mono", "Menlo", "monospace"],
      },
      fontSize: {
        "2xs": ["10px", { lineHeight: "14px" }],
        "xs":  ["11px", { lineHeight: "16px" }],
      },
      borderRadius: {
        xs:    "var(--r-xs)",
        sm:    "var(--r-sm)",
        DEFAULT: "var(--r-md)",
        md:    "var(--r-md)",
        lg:    "var(--r-lg)",
        xl:    "var(--r-xl)",
        "2xl": "var(--r-2xl)",
        full:  "var(--r-full)",
        "4xl": "2rem",
      },
      boxShadow: {
        xs:        "var(--shadow-xs)",
        sm:        "var(--shadow-sm)",
        md:        "var(--shadow-md)",
        lg:        "var(--shadow-lg)",
        float:     "var(--shadow-float)",
        glow:      "var(--shadow-glow)",
        "glow-btn":"var(--shadow-glow-btn)",
      },
      spacing: {
        "sidebar":    "var(--sidebar-w)",
        "header":     "var(--header-h)",
      },
      backgroundImage: {
        "gradient-radial":   "radial-gradient(var(--tw-gradient-stops))",
        "gradient-accent":   "linear-gradient(135deg, var(--accent) 0%, #A78BFA 100%)",
        "gradient-energy":   "linear-gradient(135deg, var(--energy) 0%, #FB923C 100%)",
        "gradient-brand":    "linear-gradient(135deg, #4F52D9 0%, #818CF8 50%, #FBBF24 100%)",
        "gradient-premium":  "linear-gradient(135deg, #7C3AED 0%, #C026D3 50%, #0891B2 100%)",
      },
      animation: {
        "fade-in":    "fadeIn 0.20s ease-out both",
        "slide-up":   "slideUp 0.30s cubic-bezier(0.16,1,0.3,1) both",
        "slide-down": "slideDown 0.30s cubic-bezier(0.16,1,0.3,1) both",
        "scale-in":   "scaleIn 0.22s cubic-bezier(0.16,1,0.3,1) both",
        "shimmer":    "shimmer 1.6s ease-in-out infinite",
        "pulse-ring": "pulseRing 2.2s ease-in-out infinite",
        "float":      "floatY 3s ease-in-out infinite",
        "spin-slow":  "spinDot 8s linear infinite",
      },
      keyframes: {
        fadeIn:    { "0%": { opacity: "0" },                              "100%": { opacity: "1" } },
        slideUp:   { "0%": { transform: "translateY(10px)", opacity: "0" }, "100%": { transform: "translateY(0)", opacity: "1" } },
        slideDown: { "0%": { transform: "translateY(-10px)", opacity: "0" },"100%": { transform: "translateY(0)", opacity: "1" } },
        scaleIn:   { "0%": { transform: "scale(0.96)", opacity: "0" },    "100%": { transform: "scale(1)", opacity: "1" } },
        shimmer:   { "0%": { backgroundPosition: "200% 0" },              "100%": { backgroundPosition: "-200% 0" } },
        pulseRing: {
          "0%, 100%": { transform: "scale(1)", opacity: "0.20" },
          "50%":       { transform: "scale(1.65)", opacity: "0" },
        },
        floatY: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%":       { transform: "translateY(-4px)" },
        },
        spinDot: {
          "from": { transform: "rotate(0deg)" },
          "to":   { transform: "rotate(360deg)" },
        },
      },
      transitionTimingFunction: {
        "spring": "cubic-bezier(0.175, 0.885, 0.32, 1.275)",
        "out":    "cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
